### ISSUE TITLE
variants dropping parts of the selector

### ISSUE THREAD

**Issue by kabalage** [tailwindcss/tailwindcss#1009]
I'm working on a plugin that would allow setting the shadow color and alpha depending on the closest parent container. For now I'll use Tailwind's class names as I'm not sure yet how I'll name mine. The concept is this:

```css
.shadow-md {
  box-shadow:
    0 4px 6px -1px hsla(var(--shadow-hue), var(--shadow-saturation), var(--shadow-lightness), var(--shadow-alpha-1)),
    0 2px 4px -1px hsla(var(--shadow-hue), var(--shadow-saturation), var(--shadow-lightness), var(--shadow-alpha-2));
}

.bg-gray-600 > * {
  --shadow-hue: 220;
  --shadow-saturation: 26%;
  --shadow-lightness: 14%;
  --shadow-alpha-1: 0.3;
  --shadow-alpha-2: 0.18;
}
```

The child combinator `>` is required because the element for which we define the background needs to cast a shadow defined in a parent.

Unfortunately this does not work when generating variants, because only `className` is used in variants. I could of course redefine all built in variants and do a custom parsing of `selector` but that does not feel right. Would appending the part that comes after the class name to the generated variant selectors break anything? What are your thoughts on this?

Keep up the good work, I like this framework a lot! :metal:
