### ISSUE TITLE
Setting opacity on placeholders in Preflight causes rendering issues in some browsers

### ISSUE THREAD

**Issue by stancl** [tailwindcss/tailwindcss#1028]
I'm trying to create a navbar using `position: fixed`, but noticed this strange issue: The placeholders of inputs on my page, but nothing else, can be seen through the navbar. Here's a jsfiddle: https://jsfiddle.net/j2cp839g/1/

I tried to rewrite this example without Tailwind, but couldn't reproduce it: https://jsfiddle.net/ewg26p3j/

When I added Tailwind back, it's broken again: https://jsfiddle.net/ewg26p3j/1/ (no Tailwind classes used).

This doesn't happen only with `fixed` but also with `absolute`.

**Comment by GeoffSelby** [comment]
This bug is coming from normalize.css it sets an opacity in input and textarea placeholders.

```css
/* From Normalize CSS */
input::placeholder,
textarea::placeholder {
  color: inherit;
  opacity: 0.5;
}
```
That opacity causes the bug but it does seem to only be with `fixed` and `absolute`. Like I said on Discord, a quick and dirty workaround is to set `z-index` on the fixed element to force it above everything.
