### ISSUE TITLE
Adding a 'streched-link' option (make parent block clickable)

### ISSUE THREAD

**Issue by paulhuisman** [tailwindcss/tailwindcss#1041]
First off, loving the framework so far, great work!

I was wondering if there's an option to add a class similar to `stretched-link` in Bootstrap 4.

https://getbootstrap.com/docs/4.3/utilities/stretched-link/

What it does is make the entire parent block clickable if you add the class to a link inside.

**Comment by AlexVipond** [comment]
I suggest making the parent block a an anchor or a button for accessibility purposes, then adding Tailwind's `group` class to create a hover group. Then, you can use the `group-hover` class on its children to customize hover styles when the parent is hovered: https://tailwindcss.com/docs/pseudo-class-variants/#group-hover

**Comment by hacknug** [comment]
I'd probably do what @AlexVipond suggested but if for some reason the link can't wrap the whole component, you can use `@apply` to create a new class that mimics Bootstrap's:

```css
.stretched-link::after {
  content: "";
  @apply z-10 absolute inset-0 bg-transparent pointer-events-auto;
}
```
