### ISSUE TITLE
Add-on for the Placeholder utility

### ISSUE THREAD

**Issue by afuno** [tailwindcss/tailwindcss#1066]
Thank you for the utility for the placeholder color.

But what about aligning the placeholder inside the field? 🙂

I mean this:

```scss
::-webkit-input-placeholder {
  text-align: center;
}

:-moz-placeholder {
  text-align: center;
}

::-moz-placeholder {
  text-align: center;
}

:-ms-input-placeholder {
  text-align: center;
}
```
