### ISSUE TITLE
[Feature Proposal] Make global font configurable

### ISSUE THREAD

**Issue by hebinet** [tailwindcss/tailwindcss#1130]
When overwriting the "Global Font" like this:
```sass
@tailwind base;
@tailwind components;

html {
    @apply text-gray-800 font-sans;
    font-weight: 400;
}

@tailwind utilities;
```

The resulting css is like this:
```css
/* Somewhere at the start of app.css */
html {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    line-height: 1.5;
}

/* Somewhere at the end of app.css */
html {
    color: #2d3748;
    font-family: -apple-system, BlinkMacSystemFont, Noway, Ubuntu, "Segoe UI", "Helvetica Neue", sans-serif;
    font-weight: 400;
}

```

The Application now uses the new font-family but there is a small "flash" when loading the site because there are 2 different style declarations for the html node.

I think the browser sees the first declaration and set the styling and later on it sees the new declaration and addapts the style acordingly.

It is even more significant if you use 2 completely different Font Families that differ in size and weight and styling.

If there would be a way to set the font-family beforehand, the flash wouldn't occure if if another font-family is set.

I saw that there was a Pull-Request for that (#930 ) but it was closed.

I think to see this flash is pretty anoying for me and the users visiting the page.
