### ISSUE TITLE
prefixed utilities on parent class condition

### ISSUE THREAD

**Issue by justijndepover** [tailwindcss/tailwindcss#1214]
Hi,

Is it possible to make a custom prefix for utility classes based on a global body class?
For example: i'd like to style a button like so:
```html
<button class="bg-teal-300 dark:bg-teal-800">...</button>
```

and the `dark:bg-teal-800` class should only be applied if the `<body>`  tag has a specific class: 
```html
<body class="darkmode">
```
So generated css should look like this:

```css
.darkmode .dark\:bg-teal-800, .darkmode.dark\:bg-teal-800 {
    background-color: #285e61;
}
```

**Comment by justijndepover** [comment]
alternatively you could add the class to the html tag to avoid the duplicate selector. Then the generated css could like a lot cleaner:
```css
.darkmode .dark\:bg-teal-800 {
    background-color: #285e61;
}
```
