### ISSUE TITLE
Register base styles plugin: object properties with same names are discarded

### ISSUE THREAD

**Issue by davidyeiser** [tailwindcss/tailwindcss#1219]
Not sure if this is a bug or intended behavior. When writing a plugin to register some `@font-face` declarations as base rules I noticed that if you use the same property name it discards the duplications and only keeps the last one.

Plugin file:

```js
module.exports = function ({ addBase, config }) {
  const webfonts = {
    '@font-face': {
      fontFamily: 'Roboto-Regular',
      src: url('path/to/file') format('woff'),
      fontStyle: 'normal',
      fontWeight: 'normal'
    },
    '@font-face': {
      fontFamily: 'Roboto-Italic',
      src: url('path/to/file') format('woff'),
      fontStyle: 'normal',
      fontWeight: 'normal'
    },
    '@font-face': {
      fontFamily: 'SomeOtherFont',
      src: url('path/to/file') format('woff'),
      fontStyle: 'normal',
      fontWeight: 'normal'
    }
  }

  return addBase(webfonts)
}
```

Outputs this CSS:

```css
@font-face {
  font-family: SomeOtherFont;
  …
}
```

Whereas I would expect this:
```css
@font-face {
  font-family: Roboto-Regular;
  …
}

@font-face {
  font-family: Roboto-Italic;
  …
}

@font-face {
  font-family: SomeOtherFont;
  …
}
```

**However**, if you add a CSS comment as part of the object property name it works as intended. And in this case it actually turns out to be kind of helpful, but wanted to report his anyways in case it's a bug.

```js
module.exports = function ({ addBase, config }) {
  const webfonts = {
    '@font-face /* body */': {
      fontFamily: 'Roboto-Regular',
      src: url('path/to/file') format('woff'),
      fontStyle: 'normal',
      fontWeight: 'normal'
    },
    '@font-face /* body-italic */': {
      fontFamily: 'Roboto-Italic',
      src: url('path/to/file') format('woff'),
      fontStyle: 'normal',
      fontWeight: 'normal'
    },
    '@font-face /* title */': {
      fontFamily: 'SomeOtherFont',
      src: url('path/to/file') format('woff'),
      fontStyle: 'normal',
      fontWeight: 'normal'
    }
  }

  return addBase(webfonts)
}
```
