### ISSUE TITLE
[ Problem ] Compiling Stylus with Laravel Mix

### ISSUE THREAD

**Issue by olavoasantos** [tailwindcss/tailwindcss#122]
Hey everybody. How are you?

I'm getting some weird behavior when I try to compile Stylus stylesheet using Laravel Mix.

My input file is:

```styl
      // resources/assets/stylus/app.styl

      @tailwind preflight;
      @tailwind utilities;

      .card {
          @apply .max-w-sm .rounded .overflow-hidden .shadow-lg;
      }
```

As instructed on the docs, my Mix config file is set to:

```js
      // webpack.mix.js

      mix.stylus('resources/assets/stylus/app.styl', 'public/css')
            .options({
               postCss: [ tailwindcss('./tailwind.config.js') ],
            });
```

And the output file is:

```css
    // public/css/app.css

    // ... Around line 3639

    @apply .max-w-sm .rounded .overflow-hidden .shadow-lg;

    // ... Rest of the file
```

This works perfectly on SASS. Any ideas on how to fix this?

**Comment by adamwathan** [comment]
Hmm this is a bummer, it seems like Stylus doesn't recognize the `@apply` at-rule and compiles things all screwed up as a result.

Exploring work-arounds for this but haven't come up with anything yet.

**Comment by adamwathan** [comment]
I've raised an issue on the Stylus repo, can follow it there:

https://github.com/stylus/stylus/issues/2335

**Comment by olavoasantos** [comment]
Thanks for the quick reply, @adamwathan!

I got it working by running Tailwind first and running Stylus later. Not a good solution, but if someone absolutely needs to use Stylus, this should work.

```styl
// resources/assets/stylus/app.styl

@tailwind preflight;
@tailwind utilities;

.card {   
    & {
        @apply .max-w-sm .rounded .overflow-hidden .shadow-lg;
    }

    &:hover {
        @apply .bg-black;
    }
}
```
And your webpack.mix.js:

```js
// webpack.mix.js

mix.stylus('resources/assets/tailwind/app.styl', 'public/css')
      .postCss('resources/assets/stylus/app.styl', '../resources/assets/tailwind/app.styl', [
          tailwindcss('./tailwind.config.js')
      ]);
```

Run this once and you'll get an error (from the `.stylus(...)`) and an `app.styl` from the `postCss` bit:

```styl
    // ...Around line 3639
  .card {
    & {
      max-width: 30rem;
      border-radius: .25rem;
      overflow: hidden;
      -webkit-box-shadow: 0 15px 30px 0 rgba(0, 0, 0, 0.11), 0 5px 15px 0 rgba(0, 0, 0, 0.08);
              box-shadow: 0 15px 30px 0 rgba(0, 0, 0, 0.11), 0 5px 15px 0 rgba(0, 0, 0, 0.08);
    }

    &:hover {
      background-color: #222b2f;
    }
  }

  // ...Rest of the file
```

Run `npm run dev` again, and you'll get an `public/css/app.css`:

```css
    /* ./public/css/app.css */
    /* ...Around line 3540 */

  .card {
    max-width: 30rem;
    border-radius: 0.25rem;
    overflow: hidden;
    -webkit-box-shadow: 0 15px 30px 0 rgba(0, 0, 0, 0.11), 0 5px 15px 0 rgba(0, 0, 0, 0.08);
    box-shadow: 0 15px 30px 0 rgba(0, 0, 0, 0.11), 0 5px 15px 0 rgba(0, 0, 0, 0.08);
  }

  .card:hover {
    background-color: #222b2f;
  }

  /* ...Rest of the file */
```
