### ISSUE TITLE
### Ok, found it

### ISSUE THREAD

**Issue by vricop** [tailwindcss/tailwindcss#1307]
### Ok, found it

```css
/**
  * 1. Fallback content
  * 2. Apply text content by retrieving the value
  *    from `data-content` HTML attribute.
  * 3. Property to apply to the generated content.
  *    `display`, `border`, etc.
  */
.before\:inline-block::before {
  content: ''; /* 1 */
  content: attr(data-content); /* 2 */
  display: inline-block; /* 3 */
}
```
If `data-content` is not set, fallback to the first content line.

```html
<button class="before:inline-block" data-content="👍">
  Like
</button>
```

[Codepen demo](https://codepen.io/vrico/pen/VwYxpWJ)

_Originally posted by @vricop in https://github.com/tailwindcss/tailwindcss/issues/1306#issuecomment-573226897_
