### ISSUE TITLE
[Feature Proposal] Add negative/positive as variants option for margin

### ISSUE THREAD

**Issue by freemagee** [tailwindcss/tailwindcss#1332]
I really like using the `variants` setting in config to control what CSS is generated. I am working on a smaller project where I am really trying to cut down a lot of the styles Tailwindcss generates. There is one area that stood out to me, the negative margins. This small project definitely would not need them.

My thoughts were both *positive* and *negative* styles are generated by default, but you could use something like this to only output the *positive* values if you wanted.

```
  variants: {
    margin: ["positive"]
  },
```

I think there are approx. 126 styles generated for `.-m*` with the default config. A small shaving I admit :)

I am obviously not sure that this meets the ethos of `variants` so if it doesn't, that is fair.

**Comment by royvanv** [comment]
> I really like using the `variants` setting in config to control what CSS is generated. I am working on a smaller project where I am really trying to cut down a lot of the styles Tailwindcss generates.

If you really want to cut down the file size, I think you should consider PurgeCSS to remove all unused classes. Alternatively you could specify the margins in your `tailwind.config.js` file.

**Comment by freemagee** [comment]
Hi @royvanv, thanks for the feedback.

I agree that PurgeCSS will inevitably help. I know there will be a bunch of classes I am not going to use, but this instance caught my attention as more of "prevention" versus a "treatment".

I have added custom margins to the theme -> spacing property. Tailwindcss seems to generate the negative margins automatically. So that may not be the answer.

```
spacing: {
      px: "1px",
      "0": "0",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem"
    }
```

Excerpt of the css it produces below:

```css
.m-0 {
  margin: 0;
}

.m-1 {
  margin: 0.25rem;
}

.m-2 {
  margin: 0.5rem;
}

.m-3 {
  margin: 0.75rem;
}

.m-4 {
  margin: 1rem;
}

.m-5 {
  margin: 1.25rem;
}

.m-6 {
  margin: 1.5rem;
}

.m-8 {
  margin: 2rem;
}

.m-10 {
  margin: 2.5rem;
}

.m-12 {
  margin: 3rem;
}

.m-16 {
  margin: 4rem;
}

.m-20 {
  margin: 5rem;
}

.m-auto {
  margin: auto;
}

.m-px {
  margin: 1px;
}

.-m-1 {
  margin: -0.25rem;
}

.-m-2 {
  margin: -0.5rem;
}

.-m-3 {
  margin: -0.75rem;
}

.-m-4 {
  margin: -1rem;
}

.-m-5 {
  margin: -1.25rem;
}

.-m-6 {
  margin: -1.5rem;
}

.-m-8 {
  margin: -2rem;
}

.-m-10 {
  margin: -2.5rem;
}

.-m-12 {
  margin: -3rem;
}

.-m-16 {
  margin: -4rem;
}

.-m-20 {
  margin: -5rem;
}

.-m-px {
  margin: -1px;
}
```
