### ISSUE TITLE
Old IE Browser's hacks not interpreted correctly

### ISSUE THREAD

**Issue by Macxim** [tailwindcss/tailwindcss#1383]
Source: 

```css
.selector {
  display: inline-block;
  *vertical-align: auto;
  *zoom: 1;
  *display: inline;
}
```

It's interpreted as:

```css
.selector {
  display: inline-block;
  vertical-align: auto;
  zoom: 1;
  display: inline;
}
```

See the demo here: https://tailwind.run/y2T2vh/1

**Comment by royvanv** [comment]
IE hacks, are those still used in 2020?

The fix is to prefix with an extra asterisk.

```css
span.emoji {
  display: inline-block;
  **vertical-align: auto;
  **zoom: 1;
  **display: inline;
}
```
