### ISSUE TITLE
Wrong property compiled with @variants

### ISSUE THREAD

**Issue by nicooprat** [tailwindcss/tailwindcss#1423]
Hi there, thanks for your hard work.

I'm trying to use `@variants` and seeing some weird results... 

### Actual results

Here is the CSS:

```css
.test1 {
  @variants hover {
    opacity: .5;
  }
}

@variants hover {
  .test2 {
    opacity: .5;
  }
}

@variants hover {
  .test3 {
    @apply opacity-50;
  }
}
```

Here's what's get compiled:

```css
.test1 {
  opacity: .5;
  opacity: .5
}

.test2 {
  opacity: .5;
}

.hover\:test2:hover {
  opacity: .5;
}

.test3 {
  opacity: 0.5;
}

.hover\:test3:hover {
  opacity: 0.5;
}
```

### Expected results

```css
.test:hover {
  opacity: 0.5;
}
```

Here's the snippets to try the same code https://tailwind.run/FMzAxn.

What's the right way to do it? Thanks.

**Comment by adamwathan** [comment]
I think your expectations are incorrect, you would never get this generated using a variant:

```css
.test:hover {
  opacity: 0.5;
}
```

Variants generate classes like `hover:test`, they don't add pseudo-classes to bare elements. Also Tailwind doesn't automatically handle nesting for you which is why this example doesn't do anything really logical:

```css
.test1 {
  @variants hover {
    opacity: .5;
  }
}
```

This behavior is the expected and correct behavior:

```css
/* Input */
@variants hover {
  .test2 {
    opacity: .5;
  }
}

/* Output */
.test2 {
  opacity: .5;
}

.hover\:test2:hover {
  opacity: .5;
}
```

The idea behind variants is that you are taking a single-purpose utility class (like `bg-red-500` for example) and saying "I also want to generate a variant of this class that is only applied on hover" for example.

So then you end up with `bg-red-500` that makes an element red, and `hover:bg-red-500` that makes an element red on hover. Just like how `md:bg-red-500` makes an element red on medium sized screens and larger.

If you want to generate this specific CSS, don't use variants, just write the CSS you want:

```css
.test:hover {
  opacity: 0.5;
}
```
