### ISSUE TITLE
Setting important to a class breaks pseudo selectors

### ISSUE THREAD

**Issue by Log1x** [tailwindcss/tailwindcss#1445]
Looks like #1334 went unnoticed – perhaps their explanation wasn't very clear.

Setting `important` to a `.class` instead of an `#id` inside of the tailwind config breaks pseudo selectors / variants.

Here is the generated CSS for a `hover`  with `important` set to `.example`:

```css
.hover\:example:hover .hover\:bg-white:hover {
  background-color: #fff;
}

.hover\:example:hover .hover\:bg-gray-100:hover {
  background-color: #f7fafc;
}
```

Here is a running example: https://tailwind.run/egiAFu
