### ISSUE TITLE
Combining `prefix` and `important` yields unexpected results

### ISSUE THREAD

**Issue by bencorlett** [tailwindcss/tailwindcss#1450]
I'm currently integrating TW into a Magento 2 site. In previous sites, I'd do something like this for my config:

```javascript
module.exports = {
    prefix: 'tw-',
    important: true
}
```

This produces expected results:

```css
.tw-text-instagram {
  color: #E4405f !important;
}

.hover\:tw-text-instagram:hover {
  color: #E4405f !important;
}
```

This would yield expected results, although my CSS is littered with `!important` tags for each rule.

I've tried the [Important](https://tailwindcss.com/docs/configuration/#important) functionality to add a selector to increase specificity:

```javascript
module.exports = {
    prefix: 'tw-',
    important: '.page-wrapper'
}
```

❗️ This produces unexpected results:

```css
.page-wrapper .tw-text-instagram {
  color: #E4405f;
}
.hover\:page-wrapper:hover .hover\:tw-text-instagram:hover {
  color: #E4405f;
}
```

It appears that whichever plugin is being handed the CSS next is not recognising that `.page-wrapper` and is adding selectors to it as well. I would expect the following result:

```css
.page-wrapper .tw-text-instagram {
  color: #E4405f;
}
.page-wrapper .hover\:tw-text-instagram:hover {
  color: #E4405f;
}
```

Let me know if I'm onto something here or I've misconfigured this. For now, I'll just switch back to `!important` as a workaround.
