### ISSUE TITLE
Cannot select a paragraph inside an anchor tag

### ISSUE THREAD

**Issue by ahaseeb408** [tailwindcss/tailwindcss#1503]
Hi there.

I placed a paragraph inside an anchor tag because I wanted the whole element to be clickable but the paragraph wasn't selectable. After scratching my head for an hour, I was finally able to 'fix' the problem by explicitly setting the `draggable` attribute to `false` on the outer anchor **and** applying the `.select-text` class to the paragraph. 

My solution feels like a hack to me.

I think this is a Tailwind problem. It's not the default browser behavior. 

I have attached a screenshot below:

![](https://i.imgur.com/ENr3d2F.png)

**Comment by vricop** [comment]
It's semantically incorrect. An anchor tag cannot contain a paragraph tag.

I recommend you use this utility from own library: https://github.com/vricop/PetricorCSS/blob/0cf91aa5f75a72d7d5f13f3411ffccefd69f819c/utility-generators/_link-stretch.scss#L6

Set the outermost parent to `relative` an d add `link-stretch` to the link you want to “expand”.

Example:

```scss
/* CSS utility from Petricor CSS library */
.link-stretch::after {
    content: "";
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
  }
```

```html
<article>
  <h2><a class="link-atretch" href="#">Post title</a></h2>
  <img src="..." alt="" />
  <p>Post excerpt...</p>
</article>
```
Further I do about this technique: https://www.sarasoueidan.com/blog/nested-links/
