### ISSUE TITLE
space and divide utilities not working with @apply

### ISSUE THREAD

**Issue by dmarkow** [tailwindcss/tailwindcss#1599]
On 1.3.4, when trying to use something like `space-x-1` with @apply I get the following error:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

.form-inline {
  @apply flex space-x-1 items-center;
}
```

> `@apply` cannot be used with `.space-x-1` because`.space-x-1` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.space-x-1` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

https://codesandbox.io/s/priceless-euclid-2iqpt

The `dist/utilities.css` file contains the space/divide classes, so I'm not sure why `@apply` isn't picking them up.  I'm wondering if it's because the space/divide classes themselves don't have any css, as they're only used as parent selectors?

```css
.space-x-1 > :not(template) ~ :not(template) {
  --space-x-reverse: 0;
  margin-right: calc(0.25rem * var(--space-x-reverse));
  margin-left: calc(0.25rem * calc(1 - var(--space-x-reverse)))
}
```
