### ISSUE TITLE
@responsive only generate certain media queries

### ISSUE THREAD

**Issue by jack-pallot** [tailwindcss/tailwindcss#161]
It would be awesome if you could allow the responsive directive to pass in optional sizes, so you don't over generate classes if you don't need them.

I'm not sure what's possible with PostCSS, and the current setup, but something like this would be ideal:

responsive(sm, md) {
}

Or possibly with a new function, to not add too much functionality to the existing one:

responsive-only(sm, md) {
}

Thoughts? I'm happy to look into what's involved in contributing this if there's an agreement.

**Comment by psren** [comment]
```css
@media (min-widt: 700px) {
    .foo { color: red; }
}

@media (min-widt: 800px) {
    .foo { color: red; }
}

@media (min-widt: 900px) {
    .foo { color: red; }
}

@media (min-widt: 1000px) {
    .foo { color: red; }
}

@media (min-widt: 1100px) {
    .foo { color: red; }
}
```

## 5 Breakpoints

uncompressed: 276B
compressed: 108B

## 3 Breakpoints

uncompressed: 166B
compressed: 101B

## Implication

The test is just a quick test and not really accurate.
But as you can see the difference in the GZIP compressed file is minimal.
I think the effort you have to put into this is maybe too big.

If you want to reduce the filesize, maybe try to remove breakpoints instead?
This will remove many more lines of code.

It seems inconvinient to have the utilities just for some breakpoints.
"Why does md:... not work but lg:... works?"
