### ISSUE TITLE
Utility for text-shadow?

### ISSUE THREAD

**Issue by HapLifeMan** [tailwindcss/tailwindcss#162]
Hey, what about create an utility for `text-shadow`? :)

**Comment by pedroborges** [comment]
I also needed it on a project and added them based on `shadow` utility for now:

```
@responsive {
  .text-shadow {
    text-shadow: 0 2px 4px rgba(0,0,0,0.10);
  }

  .text-shadow-md {
    text-shadow: 0 4px 8px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.08);
  }

  .text-shadow-lg {
    text-shadow: 0 15px 30px rgba(0,0,0,0.11), 0 5px 15px rgba(0,0,0,0.08);
  }

  .text-shadow-none {
    text-shadow: none;
  }
}
```

**Comment by adamwathan** [comment]
We're not opposed to adding this at some point, but going to skip it for now since it's so easy to add utilities yourself.

We may revisit this sooner once we've made it easy to opt in/out of different modules.

**Comment by kharysharpe** [comment]
bump @adamwathan

**Comment by kharysharpe** [comment]
@adamwathan is this still going to be considered?

**Comment by hacknug** [comment]
You can use @benface's plugin for this: https://github.com/benface/tailwindcss-typography

**Comment by justingolden21** [comment]
Just commenting in 2020 that this little utility is still welcome : )

**Comment by d4h0** [comment]
Hi @adamwathan. Yes, this is easy to add. But what are the disadvantages of adding a few more utility classes to Tailwind? Why should all Tailwind users, who need this, add it themselves?

I guess, the situation has changed in the meantime, and there wouldn't be any disadvantage today to add more utility classes.

**Comment by JonathanSchndr** [comment]
I thought this was the concept of tailwind, can you please explain again why exactly no text shadow is added? @adamwathan thanks!!

**Comment by pottz91** [comment]
we need text shadow but not with an extra module, which is still working fine.

**Comment by Ande-Mia** [comment]
Hi, 
I'm a beginner of web-design and tailwind.
I'd like to add text-shadow and read https://github.com/tailwindlabs/tailwindcss/issues/162#issuecomment-343140655 and https://tailwindcss.com/docs/functions-and-directives#responsive , but could not understand where to write the code.
The code (in `index.css`) does not work.
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

@layer components{
    @responsive {
        .text-shadow {
          text-shadow: 0 2px 4px rgba(0,0,0,0.10);
        }
      
        .text-shadow-md {
          text-shadow: 0 4px 8px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.08);
        }
      
        .text-shadow-lg {
          text-shadow: 0 15px 30px rgba(0,0,0,0.11), 0 5px 15px rgba(0,0,0,0.08);
        }
      
        .text-shadow-none {
          text-shadow: none;
        }
      }
}
```
Could anyone help me?
