### ISSUE TITLE
[v1.4] Turning off opacity in corePlugins config still generates CSS variables

### ISSUE THREAD

**Issue by pheuter** [tailwindcss/tailwindcss#1670]
The generated CSS file has increased substantially in size (~40%) as a result and I can't seem to turn it off.

**tailwind.config.js**
```js
corePlugins: {
    divideOpacity: false,
    backgroundOpacity: false,
    borderOpacity: false,
    placeholderOpacity: false,
    textOpacity: false
}
```

**Generated CSS**
```css
a {
  --text-opacity: 1;
  color: rgba(255, 128, 153, var(--text-opacity));
}

.divide-black > :not(template) ~ :not(template){
  --divide-opacity: 1;
  border-color: rgba(51, 51, 51, var(--divide-opacity));
}

.bg-black{
  --bg-opacity: 1;
  background-color: rgba(51, 51, 51, var(--bg-opacity));
}
```
