### ISSUE TITLE
Refer to colors through a variable instead of them being hardcoded. 

### ISSUE THREAD

**Issue by jonathan-s** [tailwindcss/tailwindcss#1756]
I write some html using tailwindcss using some color. I then need to customize some part and write some custom CSS using the color `indigo-500`. To be able to do that I would need to look up the actual hex code for `indigo-500` and use that.

Instead I would like to be able to do the following. 

```css
.something-custom {
  color: var(--indigo-500);
  ...snip
}
```
