### ISSUE TITLE
Allow transpilation of reverse variable in space between utils 

### ISSUE THREAD

**Issue by jonaskuske** [tailwindcss/tailwindcss#1825]
The Custom Properties plugin that's included with postcss-preset-env can only transpile CSS variables if the default value is either set on `:root` or supplied as an actual fallback value to `var()`.

This means the class Tailwind generates as of now:

```css
.space-y-4 > :not(template) ~ :not(template) {
  --space-y-reverse: 0;
  margin-top: calc(1rem * calc(1 - var(--space-y-reverse)));
  margin-bottom: calc(1rem * var(--space-y-reverse));
}
```

...can't be transpiled, but those two versions can:

```css
:root {
  --space-y-reverse: 0;
}
.space-y-4 > :not(template) ~ :not(template) {
  margin-top: calc(1rem * calc(1 - var(--space-y-reverse)));
  margin-bottom: calc(1rem * var(--space-y-reverse));
}
```
```css
.space-y-4 > :not(template) ~ :not(template) {
  margin-top: calc(1rem * calc(1 - var(--space-y-reverse, 0)));
  margin-bottom: calc(1rem * var(--space-y-reverse, 0));
}
```

<br>

Also, Internet Explorer does not like nested calls to `calc()` which apparently are  unnecessary anyway: https://codepen.io/zachhanding/post/nested-calc-functions-and-ie11.

So instead of
```
calc(1rem * calc(1 - var(--space-y-reverse, 0)));
```
it should look like:
```
calc(1rem * (1 - var(--space-y-reverse, 0)));
```
This change is not as important however, as during minification cssnano automatically removes all inner calls to `calc()` and replaces them with simple parentheses – so as long as you minify, you're good.

Any reason not to use one of the two proposed solutions? It'd make it easy to use space  between utilities in IE. (just `reverse` wouldn't work)
