### ISSUE TITLE
Bug report: Creating variants of classes with selectors that are not classes

### ISSUE THREAD

**Issue by paulpopus** [tailwindcss/tailwindcss#1833]
Hi, I've opened this as a bug report but I'm not entirely clear if it should be a feature request instead.

I've been trying to use `@variants` or `@responsive` directives to generate responsive classes for my flex-fallback grid utility.

Example code:

```css
@responsive {
  .flex-grid-4 {
    > div {
      max-width: 25%;
      @apply mr-5;

      &:last-of-type {
        @apply mr-0;
      }
    }
  }
}
```
I would expect this to generate the usual responsive classes with this ruleset however by using `div` and `:last-of-type` instead of a class selector I get this error on compilation
```bash
(33:5) Variant cannot be generated because selector contains no classes.
```
I think the current way to get around this is to write a plugin but I'd like to know if the way variant directives currently work is intended or not and I'll try to open a PR.

If you are encountering this issue, the way you can work around it is to write a plugin, for example
```javascript
plugin(function({ addComponents, theme }) {
      const flexGrid = {
        '@variants responsive': {
          '.flex-grid-4': {
            '> div': {
              maxWidth: '25%',
              'margin-right': theme('spacing.5'),
            }
          },
        }
      }
      addComponents(flexGrid)
    })
```

**Comment by estevanmaito** [comment]
You need to add nesting support to Post CSS for it to work https://tailwindcss.com/docs/using-with-preprocessors/#nesting

Adding `postcss-nested`  to your `postcss.config.js` would solve. Note that contrary to the advice in the docs, I had to place the `postcss-nested` require *before* Tailwind:

```js
module.exports = {
  plugins: [
    require('postcss-nested'),
    require('tailwindcss'),
    ...
```

The resulting CSS:

```css
.flex-grid-4>div{max-width:25%;margin-right:1.25rem}
.flex-grid-4>div:last-of-type{margin-right:0}
```

**Comment by paulpopus** [comment]
@estevanmaito thanks for that suggestion.

That does indeed work, when you add another layer to it though, it doesn't compile properly.

So if I write
```css
@responsive {
  .flex-grid-4 {
    > div {
      max-width: 25%;
      @apply mr-5;

      &:last-of-type {
        @apply mr-0;
      }
    }

    @supports (display: grid) {
      @apply bg-black;
    }
  }
}
```
This compiles without errors but it compiles to
```
.flex-grid-4>div{max-width:25%;margin-right:1.25rem}.flex-grid-4>div:last-of-type{margin-right:0}@supports (display:grid){@apply bg-black}
```

Which is obviously wrong. I also tried using the variants option, which yields better results but still dodgy.
```
@responsive {
  .flex-grid-4 {
    ...

    @variants supports-grid {
      @apply bg-black;
    }
  }
}
```
Compiles to
```
.flex-grid-4{background-color:#00131d;@supports (display:grid){background-color:#00131d}}
```

Anyway, I needed more functionality and to repeat less code so I opted to write a plugin instead and I have this as part of my code right now which will generate the classes with responsive variants and the @supports correctly.
```
function loopThroughColumns(){
  const rules = []

  // Build our list of rules by looping through the number of columns we need to support,
  // Currently this is the best way I've found
  for(col = 0; col <= numberOfColumns; col++) {
    const rule = {
      '@variants responsive': {
        [`.flex-grid-${col}`]: {
          '> div': {
            maxWidth: `${100 / col - (parseInt(gridColumnGap) * col)}%`,
            'margin-right': gridColumnGap,
            'margin-bottom': gridRowGap,
            ':last-of-type': {
              'margin-right': '0',
            }
          },
          '@supports (display: grid)': {
            'grid-template-columns': theme(`gridTemplateColumns.${col}`),
            'column-gap': gridColumnGap,
            'row-gap': gridRowGap,
            '> div': {
              maxWidth: '100%',
              'margin-right': '0',
              'margin-bottom': '0',
            }
          }
        },
      }
    }
    rules.push(rule)
  }

  return rules;
}
```

**Comment by laymonage** [comment]
I had a (not-so) similar issue, but I wasn't working with any nested rules. I was trying to do something like:

```css
a {
  @apply text-blue-700;
}

@variants dark {
  a {
    @apply text-blue-300;
  }
}
```

Compilation fails with the following error:

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'value' of undefined
```

It turns out that the following works:

```css
a {
  @apply text-blue-700;
  @variants dark {
    @apply text-blue-300;
  }
}
```

Looking at it again, I guess I misunderstood how `@variants` works. However, I think the [documentation](https://tailwindcss.com/docs/functions-and-directives/#variants) could be more clearer about this.

@estevanmaito I'm using your [tailwindcss-multi-theme](https://github.com/estevanmaito/tailwindcss-multi-theme) plugin btw. It's a great and simple plugin! :+1:
I was looking for a solution and came across this issue. (Maybe it might be a good idea to include this in your docs?)

**Comment by estevanmaito** [comment]
@laymonage I'll update the docs to include this possibility. Thanks for pointing!

**Comment by adamwathan** [comment]
@paulpopus This works totally fine for me if I manually flatten the nesting before feeding it into Tailwind:

```css
@responsive {
  .flex-grid-4 > div {
    max-width: 25%;
    @apply mr-5;
  }
  .flex-grid-4 > div:last-of-type {
    @apply mr-0;
  }
}
```

I suspect the issue is that you aren't running a nesting plugin before running Tailwind, as Tailwind itself is not nesting-aware so it is probably falling over because it thinks it is dealing with invalid CSS.

**Comment by paulpopus** [comment]
@adamwathan yeah I think that's right. I'll close the ticket, thanks to everyone who commented.

**Comment by adamwathan** [comment]
@laymonage Yeah it sounds like you've misunderstood what variants are for. They aren't for making a selector do different things under different conditions, rather they are for generating extra variants of a selector that do the _same_ thing but _only_ under that condition.

For example:

```css
@variants hover {
  .bg-black {
    background: #000;
  }
}
```

...generates this CSS:

```css
.bg-black { background: #000 }
.hover\:bg-black:hover { background: #000 }
```

Notice how both selectors make the background the same color, and the variants feature just generated the extra hover version so you can set the background to black specifically when something is hovered.

For making one selector do different things under different conditions, you just want to write regular old CSS like you discovered 👍
