### ISSUE TITLE
Adding placeholder variants with plugin returns unexpected results

### ISSUE THREAD

**Issue by estevanmaito** [tailwindcss/tailwindcss#1855]
Using Tailwind `1.4.6`

`tailwind.config.js`
```js
...
variants: {
  placeholderColor: ['dark'],
},
plugin(function ({ addVariant, theme, e }) {
  addVariant('dark', ({ modifySelectors, separator }) => {
    modifySelectors(({ className, selector }) => {
      return `'.theme-dark .${e(`dark${separator}${className}`)}`
    })
  })
})
...
```
These are the Tailwind classes generated for placeholder (just for pink-900):

```css
.placeholder-pink-900::-webkit-input-placeholder {
  --placeholder-opacity: 1;
  color: #702459;
  color: rgba(112, 36, 89, var(--placeholder-opacity));
}

.placeholder-pink-900::-moz-placeholder {
  --placeholder-opacity: 1;
  color: #702459;
  color: rgba(112, 36, 89, var(--placeholder-opacity));
}

.placeholder-pink-900:-ms-input-placeholder {
  --placeholder-opacity: 1;
  color: #702459;
  color: rgba(112, 36, 89, var(--placeholder-opacity));
}

.placeholder-pink-900::-ms-input-placeholder {
  --placeholder-opacity: 1;
  color: #702459;
  color: rgba(112, 36, 89, var(--placeholder-opacity));
}

.placeholder-pink-900::placeholder {
  --placeholder-opacity: 1;
  color: #702459;
  color: rgba(112, 36, 89, var(--placeholder-opacity));
}
```

This is what is generated for the same color. Note the lack of `::placeholder` and all the other browser variants:

```css
.theme-dark .dark\:placeholder-pink-900 {
  --placeholder-opacity: 1;
  color: #702459;
  color: rgba(112, 36, 89, var(--placeholder-opacity));
}
```

The documentation for `modifySelectors` (https://tailwindcss.com/docs/plugins/#basic-variants) say:

> The `modifySelectors` helper accepts a function that receives an object that can be destructured into the following parts:
>
> `selector`, the complete unmodified selector for the current rule
> `className`, the class name of the current rule _with the leading dot removed_ 👈

Logging `selector` results in: `.placeholder-pink-900::placeholder`

Logging `className` results in: `placeholder-pink-900` when I expect `placeholder-pink-900::placeholder`

Another problem (related, but think it could be another issue) is that if you try to create a focus variant, there's no way to place `:focus` between the selector and the pseudo-element, like: `.dark:placeholder-pink-900:focus::placeholder`
