### ISSUE TITLE
@screen returns malformed css in development mode

### ISSUE THREAD

**Issue by motleydev** [tailwindcss/tailwindcss#1860]
**Stack:**
Tailwind 1.4.6
NextJs: 9.4.1-canary.5

I have this class defintion in my style sheet:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
@tailwind screens;
/* ... some other classes including @apply, etc */
.filter-bar {
  top: 100px;
  @screen sm {
    max-height: calc(100vh - 100px);
  }
}
```

Which outputs this CSS (per chrome inspector) when in developer mode:

```css
.filter-bar {
    top: 100px;
    @media (min-width: 640px) {;
    max-height: calc(100vh - 100px);
    }: ;
}
```
Note specifically `@media (min-width: 640px) {;`

When I build the project, the correct CSS is produced, when I run the project in development mode I get that malformed CSS. Any ideas where I could look to see what's causing the issue?

My postcss config:

```js
module.exports = {
  plugins: [
    "tailwindcss",
    "postcss-preset-env",
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        autoprefixer: {
          flexbox: "no-2009",
        },
        stage: 3,
        features: {
          "custom-properties": false,
        },
      },
    ],
  ],
};
```

and my tailwind purgecss definition:

```js
purge: {
    content: [
      "./pages/**/*.{js,jsx,ts,tsx}",
      "./components/**/*.{js,jsx,ts,tsx}",
    ],
    defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],

    // These options are passed through directly to PurgeCSS
    options: {
      whitelist: ["bg-red-500", "px-4"],
    },
  },
```

Thanks!

**Comment by estevanmaito** [comment]
It would be great if you could share some reproducible case.

I have some projects using Tailwind and Next, using the same versions as you (except for the canary version of Next) and don't have this problem.

If you could share the content of your `next.config.js` file, it could help too. As you say the problem only occurs in dev mode, it could have something to do with Webpack HMR.

**Comment by adamwathan** [comment]
You need to use some sort of nesting plugin if you're going to nest your CSS like that. I thought `postcss-preset-env` would handle it but seems like maybe not? Also very odd that you have that plugin in your config twice?

Anyways either add a nesting plugin or rewrite your CSS like this so it's valid:

```css
.filter-bar {
  top: 100px;
  @screen sm {
    max-height: calc(100vh - 100px);
  }
}
@screen sm {
  .filter-bar {
    max-height: calc(100vh - 100px);
  }
}
```
