### ISSUE TITLE
Can't use pseudo class in utility

### ISSUE THREAD

**Issue by jlurena** [tailwindcss/tailwindcss#1888]
Hi,

Not sure if this isn't supported or not but seems tailwind ignores my utility classes.

Say I have the following plugin function:

```js
plugin(({ addUtilities, config }) => {
  const buttons = {
    '.btn': {
      padding:           '.5rem 2rem',
      'text-decoration': 'none',
      'min-width':       config('theme.minWidth.button'),
      'text-align':      'center',
      'border-radius':   config('theme.borderRadius.button-primary'),
      '&:hover': {
         'background-color': 'red'
       }
    },
    '.primary': {
      'background-color': config('theme.colors.brand-color'),
      color:              config('theme.colors.white'),
      border:             `2px solid ${config('theme.colors.brand-color')}`
    }
  };

  addUtilities(buttons);
})
```

I expect to get the following whenever I use `@apply btn primary`:

```scss
.my-btn {
  @apply btn primary;
}
```

``` css
.my-btn {
  max-width: 12rem;
  min-height: 3.5rem;
  margin-top: 1rem;
  padding: .5rem 2rem;
  text-decoration: none;
  min-width: 6rem;
  text-align: center;
  border-radius: 1.25rem;
  background-color: #00d068;
  color: #fff;
  border: 2px solid #00d068;
}

.my-btn:hover {
  background-color: red
}
```

This is obviously not working, my question is whether what I am trying to do is possible or not.

Thanks
