### ISSUE TITLE
Arrow with :before/:after?

### ISSUE THREAD

**Issue by frederikhors** [tailwindcss/tailwindcss#1894]
Do you plan to add arrows in the future?

Like this:

```css
.danger-arrow-top {
  position: relative;
}

.danger-arrow-top:before {
  content: "";
  position: absolute;
  left: 10px;
  top: -20px;
  border-top: 10px solid transparent;
  border-right: 10px solid transparent;
  border-bottom: 10px solid undefined;
  border-left: 10px solid transparent;
}
```
