### ISSUE TITLE
animate.css, errror: `@apply` cannot be used with .animate__animated because .animate__animated is included in multiple rulesets.

### ISSUE THREAD

**Issue by frederikhors** [tailwindcss/tailwindcss#1897]
I'm trying to use @apply with [`animate.css`](https://github.com/animate-css/animate.css).

This is my _index.css_:

```css
@import "tailwindcss/base";
@import "tailwindcss/components";

@import "animate.css/animate";

@import "./custom";

@import "tailwindcss/utilities";
```

_custom.css_:

```css
.myCustomAnimation {
  @apply animate__animated;
  @apply animate__bounce;
}
```

It gives me error:

```shell
[!] (plugin postcss) CssSyntaxError: C:\custom.css:15:3: `@apply` cannot be used with .animate__animated because .animate__animated is included in multiple rulesets.
```

I wanna use it because `animate.css` classes are too verbose.

How can I do?

**Comment by estevanmaito** [comment]
This is a limitation of `@apply`. You can find more info in Adam's past responses below:

https://github.com/tailwindcss/discuss/issues/155#issuecomment-402467947
https://github.com/tailwindcss/tailwindcss/issues/1599#issuecomment-618531722
https://github.com/tailwindcss/tailwindcss/issues/1344#issuecomment-580727001

I don't know about the `animate__animated` selector but `animate__bounce` probably refers to a `@keyframe` and it breaks `@apply`

But you could use this plugin [bentzibentz/tailwindcss-animate.css](https://github.com/bentzibentz/tailwindcss-animate.css)

**Comment by adamwathan** [comment]
Yeah as mentioned applying complex selectors is currently not supported. The error is correct, `animate__animated` appears in more than one ruleset, and apply only knows how to inline declarations from simple classes that have a single definition.

Here is some code from animate.css:

```css
.animate__animated {
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-duration: var(--animate-duration);
  animation-duration: var(--animate-duration);
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}
.animate__animated.animate__infinite {
  -webkit-animation-iteration-count: infinite;
  animation-iteration-count: infinite;
}
.animate__animated.animate__repeat-1 {
  -webkit-animation-iteration-count: 1;
  animation-iteration-count: 1;
  -webkit-animation-iteration-count: var(--animate-repeat);
  animation-iteration-count: var(--animate-repeat);
}
```

If you write this code, what would you expect the actual CSS output to be?

```css
.foo {
  @apply animate__animated;
}
```

Would it be this?

```css
.foo {
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-duration: var(--animate-duration);
  animation-duration: var(--animate-duration);
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}
```

Or this?

```css
.foo {
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-duration: var(--animate-duration);
  animation-duration: var(--animate-duration);
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}
.foo.animate__infinite {
  -webkit-animation-iteration-count: infinite;
  animation-iteration-count: infinite;
}
.foo.animate__repeat-1 {
  -webkit-animation-iteration-count: 1;
  animation-iteration-count: 1;
  -webkit-animation-iteration-count: var(--animate-repeat);
  animation-iteration-count: var(--animate-repeat);
}
```

Or something else?

It's pretty complicated to come up with intuitive behavior for this stuff which is why we've punted on it for now and explicitly errored when someone tries to use apply in an unsupported way.

Closing this as this has been discussed in the past and no concrete plans to support more complex use cases like this any time soon. We are honestly more likely to deprecate apply than we are to improve it.
