### ISSUE TITLE
[Feature Proposal] .fill-child for svg files

### ISSUE THREAD

**Issue by jenstornell** [tailwindcss/tailwindcss#1908]
I use a component approach. To fill the inline SVG icon color I use `fill-current` all the time.

```html
<svg class="fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"></svg>
```

I import the SVG files to stay organized. The downside to the approach is that I actually need to add the class to every SVG file.

### Suggestion

To get around this issue, a `.fill-child` could be introduced. It could work like below.

```html
<div class="fill-child text-red-500">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"></svg>
</div>
```

```css
.fill-child > * {
  fill: currentColor;
}
```

...or possibly...

```css
.fill-child > svg {
  fill: currentColor;
}
```

(I'm aware that we can customize this ourselves as well)
