### ISSUE TITLE
Nested Rounded Borders Hover Breaks Wrapping Border

### ISSUE THREAD

**Issue by mikebronner** [tailwindcss/tailwindcss#195]
I have noticed that when nesting rounded borders the outer border is "broken" by the inner border with a white background of squared shape after leaving the hover state. I noticed this is not related to the background color -- is this perhaps a browser bug? (This currently doesn't seem to work in Chrome for some reason, still debugging that -- tested in Safari 11.0.1.)

![screen shot 2017-11-12 at 6 45 20 pm](https://user-images.githubusercontent.com/1791050/32707570-ad445736-c7d9-11e7-83ba-d0dedd9d4e73.png)

```scss
.form-control-group {
        @apply .w-2/3 .flex .border .border-grey-light .rounded;

        button:not(:first-child, :last-child),
        input:not(:first-child, :last-child) {
            @apply .rounded-none .text-grey-darker;
        }

        :first-child {
            @apply .rounded .rounded-l .border .border-r .border-grey-light .text-grey-darker;
        }

        :last-child {
            @apply .rounded .rounded-r .text-grey-darker;
        }

        input:not([type=file], [type=submit], [type=button]) {
            @apply .flex-grow .border .border-grey-lightest;
        }

        input:not([type=file], [type=submit], [type=button]):hover {
            @apply .border .border-blue;
        }
}
```

```html
<div class="file-field form-control-group">
    <input type="text" name="file1" placeholder="No File Selected ..." disabled="disabled" class="form-control file-name">
    <button type="button" class="file-button">
        <input id="file1" name="file1" type="file">
        Browse ...
    </button>
</div>
```
