### ISSUE TITLE
Border-radius preflight is always aplied

### ISSUE THREAD

**Issue by jvanbaarsen** [tailwindcss/tailwindcss#215]
When I have a button: `<input type="button">` and apply the `rounded` class to it, it will still always be `border-radius: 0`.

The css that takes the highest priority is in the preflight: https://github.com/tailwindcss/tailwindcss/blob/be3f9d38505ff7be9e5f507c054c08d5cc221960/css/preflight.css#L538

**Comment by tlgreg** [comment]
Yeah, they have an element in the selector too.

This would be the best I think without fighting specificity and not creasing the size of utilities:
```css
input[type="button" i]:not([class*="rounded" i]),
input[type="submit" i]:not([class*="rounded" i]),
input[type="reset" i]:not([class*="rounded" i]),
input[type="file" i]:not([class*="rounded" i])::-webkit-file-upload-button,
button {
  border-radius: 0;
}
```
