### ISSUE TITLE
Embedded responsive breakpoint in Less renders incorrect CSS selector

### ISSUE THREAD

**Issue by aphofstede** [tailwindcss/tailwindcss#253]
Not 100% sure in which part of the pipeline this fails, but the following Less code:
```less
header.home-hero {
  .nav-link {
    @apply .block .mt-4 .mr-4 .text-white;
    &:hover {
      @apply .text-teal-light;
    }
  }
  @screen lg {
    .nav-link {
      @apply .inline-block .mt-0;
    }
  }
}
```

gets rendered to:

```css
header.home-hero .nav-link {
	display: block;
	margin-top: 1rem;
	margin-right: 1rem;
	color: #ffffff;
}

header.home-hero .nav-link:hover {
	color: #64d5ca;
}

@media (min-width: 992px) {
	.nav-link { /* <---- Expected "header.home-hero .nav-link {" */
		display: inline-block;
		margin-top: 0;
	}
}
```
