### ISSUE TITLE
Border - Top only

### ISSUE THREAD

**Issue by mikhailbot** [tailwindcss/tailwindcss#289]
Firstly, thanks for Tailwind!

I'm trying to add a `border-top` to a `div` and I'm not sure that's even possible currently... on version `0.2.2`

```html
<div class="border-t border-red">...</div>
```

...outputs...

```css
.border-red, .hover\:border-red:hover {
    border-color: #e3342f;
}

.border-t {
    border-top-width: 1px;
}
```

But this doesn't add a border as there's no border-style! So I'l add `border-solid` which should fix that...except it adds the below:

```css
.border-solid {
    border-style: solid;
    border-top-style: solid;
    border-right-style: solid;
    border-bottom-style: solid;
    border-left-style: solid;
}
```

Which works...except it also adds a border on all the other sides of the `div` of 4px!

<img width="175" alt="screen shot 2017-12-04 at 4 16 54 pm" src="https://user-images.githubusercontent.com/23411641/33576682-a75fe6e6-d90e-11e7-89b7-24ae4586e478.png">

<img width="178" alt="screen shot 2017-12-04 at 4 19 15 pm" src="https://user-images.githubusercontent.com/23411641/33576760-ed4100c8-d90e-11e7-8ba9-d7a315aded5c.png">

Am I going crazy or doing something wrong?

**Comment by mikhailbot** [comment]
Hmm think I've figured it out, relevant issue: https://github.com/adamwathan/vue-cli-tailwind-example/issues/1

**Comment by joshcoast** [comment]
I have this same problem, but I can't find what mikhailbot did to solve this? Does anyone know? The last link he posted is a 404 now.

**Comment by AlexVipond** [comment]
@joshcoast Are you experiencing this problem on the current version (1.0.4) or mikhailbot's version (0.2.2)?

**Comment by kadawatha** [comment]
Bump

**Comment by rationalthinker1** [comment]
bump.

**Comment by gkweb** [comment]
bump

**Comment by clintfisher** [comment]
Having this issue as well, and am not using vue. tailwind 2.0.3

**Comment by VTrngNghia** [comment]
> Having this issue as well (bottom border), and am not using vue. tailwind 2.0.3
> 
> I was able to work around it by adding `border-0` first in my classlist `border-0 border-b border-solid`

Not working for me (tailwind 2.1.4). the `border-0` generates a bunch of `!important` styles, so it overrides everything else

**Comment by mrwensveen** [comment]
I was having the same issue. Turned out that in my case `preflight: false` was set in `corePlugins`. Setting it to true fixed the problem (turned it off again because it broke something in my specific case). HTH.

**Comment by silverwind** [comment]
Another solution to avoid the preflight and its wildcard selectors is to add the missing `border-{dir}-style` classes, which `unocss` also has:

```css
@tailwind utilities;
@layer utilities {
  .border-b-solid { border-bottom-style: solid }
  .border-t-solid { border-top-style: solid }
  .border-l-solid { border-left-style: solid }
  .border-r-solid { border-right-style: solid }
  .border-x-solid { border-left-style: solid; border-right-style: solid }
  .border-y-solid { border-top-style: solid; border-bottom-style: solid }
}
```
