### ISSUE TITLE
Cannot @apply on .container

### ISSUE THREAD

**Issue by pxwee5** [tailwindcss/tailwindcss#298]
I want to do the following in order to quickly use a pre-set container for my flex-boxes. 
```
.container-flex {
  @apply .container .px-3 .mx-auto;
}
```

But I got:
```
`@apply` cannot be used with .container because .container is nested inside of an at-rule (@media).
```

Isn't this the sameIs `.container` not considered a utility class that can be used with `@apply`? Some explanation would be great :)

**Comment by adamwathan** [comment]
This is by design at the moment as we haven't explicitly designed and implemented support for `@apply`ing complex selectors.

Here's the definition for `.container`:

```css
.container {
  width: 100%;
}

@media (min-width: 576px) {
  .container {
    max-width: 576px;
  }
}

@media (min-width: 768px) {
  .container {
    max-width: 768px;
  }
}

@media (min-width: 992px) {
  .container {
    max-width: 992px;
  }
}

@media (min-width: 1200px) {
  .container {
    max-width: 1200px;
  }
}
```

Currently, `@apply` is designed to simply "mix in" a class into the current rule. For `@apply` to work with `.container`, it would have to duplicate the current selector and create new rules for it in media query declarations.

We might consider making `@apply` handle more complex situations like this eventually but I'm very hesitant due to how much unknown complexity there is.

`@apply` is inspired by how Less lets you use classes as mixins, and even Less doesn't generate rules like you would want in this case:

http://less2css.org/#%7B%22less%22%3A%22.container-flex%20%7B%5Cn%20%20.container%3B%5Cn%7D%5Cn%5Cn.container%20%7B%5Cn%20%20width%3A%20100%25%3B%5Cn%7D%5Cn%5Cn%40media%20(min-width%3A%20576px)%20%7B%5Cn%20%20.container%20%7B%5Cn%20%20%20%20max-width%3A%20576px%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40media%20(min-width%3A%20768px)%20%7B%5Cn%20%20.container%20%7B%5Cn%20%20%20%20max-width%3A%20768px%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40media%20(min-width%3A%20992px)%20%7B%5Cn%20%20.container%20%7B%5Cn%20%20%20%20max-width%3A%20992px%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40media%20(min-width%3A%201200px)%20%7B%5Cn%20%20.container%20%7B%5Cn%20%20%20%20max-width%3A%201200px%3B%5Cn%20%20%7D%5Cn%7D%22%7D

So for the foreseeable future, the recommended way to do what you need here is just to create a new component that behaves the way you want by hand:

```css
.container-flex {
  @apply .w-full .px-3 .mx-auto;
}
@screen sm {
    .container-flex { max-width: config('screens.sm'); }
}
@screen md {
    .container-flex { max-width: config('screens.md'); }
}
@screen lg {
    .container-flex { max-width: config('screens.lg'); }
}
@screen xl {
    .container-flex { max-width: config('screens.xl'); }
}
```

We may try to handle this intelligently in the future but for now, `@apply` is very strict by design about only support classes that have a single definition, have no pseudo-classes in their selector, and are not nested within media queries.
