### ISSUE TITLE
Border style for images defaults to none?

### ISSUE THREAD

**Issue by joeybeninghove** [tailwindcss/tailwindcss#362]
I'm not sure if this is a recent change, but it looks like `img` elements have a default `border-style` set to `none`.  In the comments for the generated CSS, it looks like this is only meant for IE 10, but it's being applied globally for all browsers.

(from the generated CSS)
```css
/**
 * Remove the border on images inside links in IE 10-.
 */

img {
  border-style: none;
}
```

This is making it so you can't just apply `border` to `img` elements to get a border, but rather `border border-solid`.  Not a huge deal, but it seems inconsistent with how borders are treated everywhere else.

Is there a particular reason borders are turned off by default for `img` elements?
