### ISSUE TITLE
Importing Sass partials that contain variants?

### ISSUE THREAD

**Issue by ooloth** [tailwindcss/tailwindcss#373]
I'm having an issue generating custom class variants using `@variants` in Sass partials. I'm using Tailwind with Gatsby and building my CSS using the Tailwind CLI.

All variants (responsive, hover, focus) are generated if I include the entire `@variant` declaration in my main Sass file like this:

```scss
/* main.scss */
@variants responsive, hover, focus {
  .test {
    color: red;
  }
}
```

However, I'd prefer to put these declarations in Sass partials and import them. Unfortunately, neither of the following approaches generates the correct variant classes:

### Include full declaration in sass partial and import it in main.scss
```scss
/* partial.scss */
@variants responsive, hover, focus {
  .test {
    color: red;
  }
}

/* main.scss */
@import 'utilities/partial.scss'
```

### Include style declaration in sass partial and import it inside `@variant` declaration in main.scss
```scss
/* partial.scss */
.test {
  color: red;
}

/* main.scss */
@variants responsive, hover, focus {
  @import 'utilities/partial.scss'
}
```

Since I assume this is a common use case, I'd love to know what I'm doing wrong!
