### ISSUE TITLE
[Feature Proposal] Pin full

### ISSUE THREAD

**Issue by chasegiunta** [tailwindcss/tailwindcss#393]
This is similar to #370 but I don't necessarily agree that pin sizes are needed, hence the new issue.
(I think the `pin-r mr-2` workaround suggested in that issue is solid.)

What I _**was**_ hoping for were options for pinning 100%.

Maybe something like:
`pin-l-full` `pin-r-full` `pin-t-full` `pin-b-full`

Submenu use-case:
![image](https://user-images.githubusercontent.com/1377169/36572474-a19cc24c-1801-11e8-8202-52fafcaedefc.png)

**Comment by illycz** [comment]
I do not want to comment class names, but I often use 50% and 100%, so I'm definitely for any solution.

**Comment by KKSzymanowski** [comment]
I was looking for something like this.
I'd like to extend this proposal even further to add a way to define custom values like for paddings:
```js
pin: {
    'half': '50%',
    'full': '100%',
    'custom': '127.36%',
},
```
Resulting in:
```css
.pin-l-half {
    left: 50%;
}
.pin-l-full {
    left: 100%;
}
.pin-l-custom {
    left: 127.36%;
}
.pin-t-half {
    top: 50%;
}
/* And so on */
```

@adamwathan, if you're interested in this, I can put together a pull request.
