### ISSUE TITLE
@variant with `::before` results in an invalid selector.

### ISSUE THREAD

**Issue by frankdejonge** [tailwindcss/tailwindcss#512]
Given:

```css
@variant hover {
  .something::before { styles: 'swifty'; }
}
```

The output is:

```
 .hover\:something::before:hover { styles: 'swifty'; }
```

But I'd expect it to be:

```
 .hover\:something:hover::before { styles: 'swifty'; }
```
