### ISSUE TITLE
@variants do not work on rules with multiple selectors

### ISSUE THREAD

**Issue by objectmastery** [tailwindcss/tailwindcss#530]
Using the @variants function with rules that have multiple selectors does not work as I expected it to.

Say I have the following CSS:

```css
@variants hover {
  .a, .b {
    color: red
  }
}
```

This is what I expect to be output:
```css
.hover\:a:hover, .hover\:b:hover {
  color: red
}
```

... but this is what I actually get:
```css
.hover\:a, .b:hover {
  color: red
}
```

In this file:
https://github.com/tailwindcss/tailwindcss/blob/37493edfc7d7118c416470fa718d8e65e1bb35f0/src/util/generateVariantFunction.js
We have this block of code:
```js
          modifySelectors: modifierFunction => {
            cloned.walkRules(rule => {
              rule.selector = modifierFunction({
                className: rule.selector.slice(1),
                selector: rule.selector,
              })
            })
            return cloned
          },
```

In my opinion, I feel like using rule.selector here is causing the unexpected behaviour.
Would it be better to map over the [rule.selectors](http://api.postcss.org/Rule.html#selectors) property instead (like below)?

```js
      modifySelectors: modifierFunction => {
        cloned.walkRules(rule => {
          rule.selectors = rule.selectors.map(selector =>
            modifierFunction({
              className: selector.slice(1),
              selector: selector
            })
          );
        });
        return cloned;
      }
```
