### ISSUE TITLE
`column-count` support

### ISSUE THREAD

**Issue by LoganDark** [tailwindcss/tailwindcss#540]
I'd appreciate Tailwind utilities for working with the `column-count` property.

Something like `.col-count-2`, or something similar.

It's great for masonry layouts:

![image](https://user-images.githubusercontent.com/4723091/44507500-aaa76080-a65f-11e8-83aa-f1119b45079d.png)

([image source](http://w3bits.com/css-masonry/))

**Comment by codytooker** [comment]
+1 to this.  I just tweeted tailwindcss before coming here asking if it was something planned.

I'd be willing to take a stab at it, if it's wanted in core at all.  If not I will look at making a plugin.

**Comment by codytooker** [comment]
@brandonpittman is there a reason you think this may be a bad idea.  The Css Columns spec has multiple selectors. 

```
column-count:
column-gap:
column-span:
column-rule:
column-width:
```

My only thought is it may product some naming conflicts with grid-column once those get added to core depending on how they are named. But that could be discussed and figured out.

Also since these selectors are seldom used the module / modules could be set to false in the default config if need be.

**Comment by codytooker** [comment]
I submitted a pull requests that is a sort of work in progress brainstorming section for the css column specification, it can be found at #541 . If anyone has some insight in how it should be handled, head over there and leave a comment.

**Comment by LoganDark** [comment]
> ```
> column-count:
> column-gap:
> column-span:
> column-rule:
> column-width:
> ```

@codytooker

```
.col-count
.col-gap
.col-span
.col-rule
.col-w
```

:)

**Comment by codytooker** [comment]
@LoganDark take a look at #541 if you look at the file changes you can see the selectors I came up with.  I was trying to model most of it after the way borders are handled currently in Tailwind.

For instance Column Fill classes are the following.
`
.column-fill
.column-balance
.column-balance-all
`

And Column Rule style classes are
`
.column-solid
.column-dashed
.column-dotted
.column-none
`

With column rule color and column count following the same convention with 
`
.column-{color}
.column-{number}
`

I do like the short hand .col but was concerned with how the grid implementation that I assume is coming to tailwind will be built.

**Comment by LoganDark** [comment]
@codytooker you really should use plain `col`.

https://tailwindcss.com/docs/flexbox-direction/#class-reference

That's the convention these guys use, and `col` is much more convenient and easy to type than `column`.

I'm pretty sure they'll use a `grid` prefix for CDD grid.

**Comment by codytooker** [comment]
Updated classes to use `.col-` instead of `.column-` in agreement with @LoganDark 's input.
changes can be seen at #541

**Comment by hacknug** [comment]
Hey there! In my opinion this should not be a part of core (not even disabled by default) but that doesn't mean it's something we don't need.

I've published a couple of plugins to NPM that would do the exact same thing your PR does plus some extra utilities related to CSS multi-columns (I've actually incorporated some of the naming conventions you discussed to what I already had before publishing).

Let me know if there's anything else you're missing here, feel free to open issues to discuss whatever and let's wait on Adam's input on this (guessing he'll pass on the PR since this is what the plugins API was built for).

- Break: https://www.npmjs.com/package/tailwindcss-break
- Multi-Column: https://www.npmjs.com/package/tailwindcss-multi-column

**Comment by adamwathan** [comment]
I think this would be better as a plugin at least for now, always can revisit later though.

> ["Rule #1 of open-source: no is temporary, yes is forever."](https://twitter.com/solomonstre/status/715277134978113536?lang=en)

**Comment by surjithctly** [comment]
Can revisit this now as a JIT plugin?

**Comment by benmarles** [comment]
+1

**Comment by disemio** [comment]
If you're planning to use this in `ul` element, [Columns](https://tailwindcss.com/docs/columns) work just fine.

**Comment by davidwebca** [comment]
For those who need this in Tailwind v4, here's what I came up with while migrating from [tailwindcss-multi-column](https://github.com/hacknug/tailwindcss-multi-column): 
https://play.tailwindcss.com/lC8MBCSicQ?file=css

```css
@import "tailwindcss";

:root{
  --tw-column-rule-style: solid;
}

@theme {
  --column-rule-style-solid: solid;
  --column-rule-style-dashed: dashed;
  --column-rule-style-dotted: dotted;
  --column-rule-style-double: double;
  --column-rule-style-none: none;
  --column-fill-auto: auto;
  --column-fill-balance: balance;
  --column-fill-all: all;
  --column-count-span-none: none;
  --column-count-span-all: all;
}
@utility col-count-*{
  column-count: --value(integer);
}
@utility col-gap-*{
  column-gap: --spacing(--value(integer));
}
@utility col-w-*{
  column-width: --spacing(--value(integer));
}
@utility col-rule-*{
  column-rule-style: var(--tw-column-rule-style);
  column-rule-color: --value(--color);
  column-rule-width: calc(--value(integer) * 1px);
  column-rule-style: --value(--column-rule-style-*);
}
@utility col-fill-*{
  column-fill: --value(--column-fill-*);
}

/* Specific name with "col-count" prefix to avoid collision with grid-column utilities */
@utility col-span-*{
  column-span: --value(--column-count-span-*);
}
```

The col-gap and col-w utilities are using a soon-to-be-added special function "--spacing()". You can read more about it [here](https://github.com/tailwindlabs/tailwindcss/pull/17308).
