### ISSUE TITLE
Utility first suggestion for .active classes

### ISSUE THREAD

**Issue by incompletude** [tailwindcss/tailwindcss#562]
Hey guys, thank you for all the hard work. I'm loving tailwind and the utility first approach.

I'm having trouble putting my head around a utility first approach to active classes like the following one. 

Any suggestions?

```html
                    <div class="hnav-button">
                        <span class="hnav-button__bar"></span>
                        <span class="hnav-button__bar"></span>
                    </div>
```

```css
.hnav-button {
    cursor: pointer;

    display: flex;
    flex-direction: column;
    align-items: flex-end;
}

.hnav-button__bar {
    width: 24px;
    height: 2px;
    margin-bottom: 6px;
    background-color: #3a3e3a;
    transform-origin: top right;
    transition: all 200ms linear;

    &:last-of-type {
        width: 16px;
        margin-bottom: 0;
        transform-origin: bottom right;
    }
}

.hnav-button.active .hnav-button__bar {
    width: 25px;
    background-color: #63d488;

    &:first-of-type {
        margin-bottom: 15px;
        transform: rotate(-45deg);
    }

    &:last-of-type {
        transform: rotate(45deg);
    }
}
```
