### ISSUE TITLE
@preflight causing issue with Google Maps InfoWindows

### ISSUE THREAD

**Issue by kylemilloy** [tailwindcss/tailwindcss#564]
In the preflight.css file on line ~540 we see:

```css
*,
*::before,
*::after {
  border-width: 0;
  border-style: solid;
  border-color: config('borderColors.default', currentColor);
}
```

The `border-style: solid;` style on the catch all (*, not its pseudo-selectors) is causing extra absolutely positioned elements in Google Maps to be broken

I have found that adding a separate selector underneath fixes the problem:

```css
* {
  border-style: inherit;
}
```

### Before `border-style: inherit;`
![screen shot 2018-10-01 at 11 28 06 am](https://user-images.githubusercontent.com/15757117/46305481-c9f2b100-c56e-11e8-83cd-57b355f34443.png)

### After adding `border-style: inherit;`
![screen shot 2018-10-01 at 11 27 05 am](https://user-images.githubusercontent.com/15757117/46305490-ce1ece80-c56e-11e8-92d9-a5646ce7902c.png)

``

**Comment by kylemilloy** [comment]
I'll write a quick pull for this...

**Comment by kylemilloy** [comment]
https://github.com/tailwindcss/tailwindcss/issues/484

**Comment by lbjones** [comment]
I've found that this rule in the preflight `border-style: solid;` oddly is making it so the buttons i'm using (https://material-components.github.io/material-components-web-catalog/#/component/button) no longer ripples when clicked.

Unfortunately I can't for the life of me figure out a workaround.  If I create my own preflight and remove that rule, I now have a huuuge application that I need to refactor that previously depended on that rule.  Hmmmmmm....

**Comment by kylemilloy** [comment]
The ::before/::after calls may be the culprit here though that's a WAG w/o seeing your work.


```scss
// Line 545 in preflight.css
*,
*::before,
*::after {
  border-width: 0;
  border-style: solid;
  border-color: config('borderColors.default', currentColor);
}
```

Maybe in `.mdc-button` you could add the following?

```scss
.mdc-button::before,
.mdc-button::after {
  border-style: inherit;
}
```

**Comment by lbjones** [comment]
Hey many thanks for the help @kylemilloy .  I have tried this and several dozen variations on this; `border-style: inherit;`, `border-style: none;`, `border-style: initial;`, `border-style: unset;`.  I also tried putting the code in all sorts of places in case it was a specificity issue.  I also tried to rewrite this rule in preflight with a bunch of `:not()` selectors.  Nothing has worked yet!  Anyway, I'll keep digging.

**Comment by kylemilloy** [comment]
And if you remove preflight it goes away? Have you tracked it specifically to the border-style issue here? Is it possible it could be an issue with some other wildcard selector like:

```scss
// Line 466
*,
*::before,
*::after {
  box-sizing: inherit;
}
```
