### ISSUE TITLE
[Feature Proposal] limit @responsive output to specifically supplied screen sizes

### ISSUE THREAD

**Issue by codemonkeynorth** [tailwindcss/tailwindcss#616]
in this code, it appears like it'll output css for every screen size
```scss
@responsive {
  .bg-gradient-brand {
    background-image: linear-gradient(blue, green);
  }
}
```

it would be useful if you could also pass a list of screen sizes to include so as not to output unnecessary  classes

thanks
J
