### ISSUE TITLE
[Feature Proposal] Reset heading styles

### ISSUE THREAD

**Issue by bradgenereux** [tailwindcss/tailwindcss#622]
Out of the box, Tailwind gives ```h1``` tags a style of  ```font-size: 2em``` through a rule defined in normalize.css. The rest of the headings are sized via the user agent.

```css

h1 { font-size: 2em; }
h2 { font-size: 1.5em; } /* user agent */
h3 { font-size: 1.17em; } /* user agent */
```
If you forget to style the font size of a heading, there's a good chance it will have a size not defined in your tailwind config. 

For this reason, I think headings should be reset to the base font size. This way you're forced to intentionally apply classes to style your headings.

```css
h1, h2, h3, h4, h5, h6 {
    font-size: 100%;
    font-weight: normal;
}
```
