### ISSUE TITLE
@screen directive is incorrectly generating css

### ISSUE THREAD

**Issue by dasZGFz** [tailwindcss/tailwindcss#781]
I am currently on `1.0.0-beta.2`.

This code:
```css
html {
  @apply bg-gray-200 antialiased;

  @screen lg {
    @apply bg-gray-900;
  }

  @screen md {
    @apply text-white;
  }
}
```

is generating this:
```css
html {
  background-color: #edf2f7;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
@media (min-width: 1024px) {
    background-color: #1a202c;
}
@media (min-width: 768px) {
    color: #fff;
}
}
```

which is incorrect syntax. Am I using @screen wrong or is this a bug?
