### ISSUE TITLE
[1.0] `theme()` helper doesn't work in complex properties

### ISSUE THREAD

**Issue by jakewtaylor** [tailwindcss/tailwindcss#831]
Hi,

I've noticed the `theme()` helper doesn't work inside CSS properties that aren't a simple `background` or `color` etc. If you use the helper in a statement with multiple values it just outputs nothing.

```CSS
/* Source */
input::-webkit-autofill {
  -webkit-box-shadow: 0 0 0 30px theme('colors.gray.200') inset !important;
}

/* Outputs */
input::-webkit-autofill {
  -webkit-box-shadow: 0 0 0 30px inset !important;
}
```

It's working fine for simple statements like `color: theme('colors.gray.200');` etc., so I'm working around it by using CSS variables like this for now:

```CSS
input::-webkit-autofill {
  --shadowColor: theme('colors.gray.200');
  -webkit-box-shadow: 0 0 0 30px var(--shadowColor) inset !important;
}
```

---

I'm using Laravel Mix to build, with the following config:
```JS
const mix = require('laravel-mix')
const tailwind = require('tailwindcss')
const glob = require('glob-all')
const cssImport = require('postcss-import')
const cssPresetEnv = require('postcss-preset-env')
const cssNested = require('postcss-nested')
const purgeCss = require('@fullhuman/postcss-purgecss')

mix
   .copyDirectory('resources/img', 'public/img')
   .copyDirectory('resources/assets/', 'public/css/assets')
   .postCss('resources/sass/styles.pcss', 'public/css', [
      cssImport(),
      tailwind('./tailwind.config.js'),
      cssNested(),
      cssPresetEnv(),
      purgeCss({
         content: glob.sync([
            path.join(__dirname, 'resources/views/**/*.blade.php'),
            // Add any other files that reference class names here
         ]),
         extractors: [{
            extractor: class {
               static extract (content) {
                  return content.match(/[A-z0-9-:\/]+/g) || [];
               }
            },
            extensions: ['html', 'js', 'php'],
         }]
      }),
   ])
   .options({
      processCssUrls: false,
   })
```

I'm not sure what the problem here is; I assume it's a bug from further up the chain in post css or something, but thought I'd post here in case that assumption is wrong.

If there's a way to get it working please let me know!
