### ISSUE TITLE
word-break vs word-wrap

### ISSUE THREAD

**Issue by franciscolourenco** [tailwindcss/tailwindcss#835]
https://next.tailwindcss.com/docs/word-break/#content
The `word-break` utilities documentation says it applies `word-break`, but its actually applying the `word-wrap` property.

I'm using v0.7.x

Is this changed in v1 or is it a bug?

**Comment by adamwathan** [comment]
Those docs are correct for v1 and the v0.7.4 docs are correct for v0.7.4, there's a few little differences in this particular module.

v0.7.4:

```css
.break-words {
  word-wrap: break-word;
}

.break-normal {
  word-wrap: normal;
}

.truncate {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

v1:

```css
.break-normal {
  overflow-wrap: normal;
  word-break: normal;
}

.break-words {
  overflow-wrap: break-word;
}

.break-all {
  word-break: break-all;
}

.truncate {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
