### ISSUE TITLE
Default border might be more pain than its worth

### ISSUE THREAD

**Issue by alphabt** [tailwindcss/tailwindcss#938]
While I appreciate the thought of making the use of border easier, but the [default border style](https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally) for all elements is causing me some pain.

When I try to style an element with a top border using normal css, it will add unexpected borders on all sides. I understand this is default behavior from tailwind, but still unexpected nevertheless.

```css
.normal-css {
  border-top-color: gray;
  border-top-style: solid;
  border-width: 1px;
}
```

![image](https://user-images.githubusercontent.com/6440237/58367604-dcfa2d00-7f13-11e9-95da-b1b6958991dd.png)

So I have to apply a workaround:

```css
.normal-css-with-workaround {
  border-style: none; /* workaround */
  border-top-color: gray;
  border-top-style: solid;
  border-width: 1px;
}
```

![image](https://user-images.githubusercontent.com/6440237/58367608-e8e5ef00-7f13-11e9-9010-454157c3c62f.png)

Of course I can just use border from tailwind:

```html
<div class="border-t">
  tailwind css
</div>
```

![image](https://user-images.githubusercontent.com/6440237/58367616-01eea000-7f14-11e9-87c0-a6fa2068c956.png)

[jsFiddle here](https://jsfiddle.net/iczman/ghb4nws0/50/)

As you can see, I am forced to either:
1. use normal css but add workaround, or
1. use tailwind border as designed, or
1. not reset border at all by foregoing preflight

I can't have them all (ie, use normal css without workaround while keeping preflight). Perhaps the default border reset deserves another around of thought?

**Comment by tlgreg** [comment]
You can assign the width to one side only.
```css
.normal-css {
  border-color: gray; /* you can leave out top here if you wish */
  border-top-width: 1px;
}
```

**Comment by alphabt** [comment]
@tlgreg am I missing anything? When I tried that it still draws all 4 borders

![image](https://user-images.githubusercontent.com/6440237/58371694-13e93680-7f46-11e9-87d5-7991ee29a55d.png)

**Comment by tlgreg** [comment]
Should work, added to your example: https://jsfiddle.net/fa634csm/

**Comment by alphabt** [comment]
Oops it works for me now. Somehow jsFiddle didn't refresh properly for me :/

**Comment by adamwathan** [comment]
Yeah that's what I was going to suggest, just setting the border width on the side you want.

I agree this is one of the gnarlier parts of Tailwind and I deliberated removing it for 1.0 but ultimately I still feel like the convenience is worth it. Would be a breaking change to remove so can't do that until 2.0 which isn't even on my radar right now.

If you want to override just that one part of Preflight, add this rule after `@tailwind base` in your own CSS:

```css
*,
*::before,
*::after {
  border-width: 1px;
  border-style: none;
}
```

It's not a perfect "undo" but it will get you back to where you want. Alternatively you can disable Preflight completely:

https://tailwindcss.com/docs/preflight/#disabling-preflight
