### ISSUE TITLE
Using @responsive with adjacent sibling selector

### ISSUE THREAD

**Issue by mattwaler** [tailwindcss/tailwindcss#947]
**Tailwind Version:** 1.0.2

When trying to create custom subsequent classes via `@responsive`, the outputted CSS is not valid. For example, this css:

```css
@responsive {
  .subseq-border + .subseq-border {
    @apply border-l;
  }
}
```

Results in this CSS:

```css
.subseq-border + .subseq-border {
  border-left-width: 1px;
}
.subseq-border + .sm\:subseq-border {
  border-left-width: 1px;
}
.subseq-border + .md\:subseq-border {
  border-left-width: 1px;
}
```

Is this something that you foresee is fixable?
