### ISSUE TITLE
preflight is heavily dictating <video></video> responsiveness

### ISSUE THREAD

**Issue by BradLockhart** [tailwindcss/tailwindcss#950]
*Clear explanation of the problem was here - 2019*

**Comment by adamwathan** [comment]
Sorry can you explain the actual problem and give an example? I’m not sure what you’re trying to do that you aren’t able to do as it’s not mentioned anywhere in your comment.

**Comment by adamwathan** [comment]
Hmm sorry if I came across as confrontational or anything, I really do want to understand the problem and help come up with a solution.

Here was the original message:

![image](https://user-images.githubusercontent.com/4323180/58747929-c1c17d00-843f-11e9-845f-ce7c682ff2c7.png)

Here are the only styles we add to the `video` tag:

```css
/**
 * Make replaced elements `display: block` by default as that's
 * the behavior you want almost all of the time. Inspired by
 * CSS Remedy, with `svg` added as well.
 *
 * https://github.com/mozdevs/cssremedy/issues/14
 */

img,
svg,
video,
canvas,
audio,
iframe,
embed,
object {
  display: block;
  vertical-align: middle;
}

/**
 * Constrain images and videos to the parent width and preserve
 * their instrinsic aspect ratio.
 *
 * https://github.com/mozdevs/cssremedy/issues/14
 */

img,
video {
  max-width: 100%;
  height: auto;
}
```

If you can give an example of something you are trying to accomplish (as a JSFiddle or Codepen link for example) that this is preventing you from accomplishing I want to help figure out a solution.

Re-reading your original message and trying to understand, is it that you are trying to create a full screen video where the video is cropped as necessary to fill the screen?

Is this kind of what you're trying to do:

https://jsfiddle.net/sud76y15/1/

If so I'd love to know how you would normally implement this without Preflight, then see if I can think of a way to make it work with it, otherwise would have to be something we save for v2 when we can make breaking changes again :/
