### ISSUE TITLE
Feature Request/question: Ability to disable 'default' variant

### ISSUE THREAD

**Issue by brookback** [tailwindcss/tailwindcss#969]
Hey! I noticed I can't disable the `default` variant for a core plugin through the Tailwind config.

**My use case is as follows:**

- I'd like to create a separate `dark-mode.css` file, for consumers to opt-in to.
- This file is generated with a separate `tailwind.config.dark-mode.js` config, which uses and extends my default config:

```js
const myDefault = require('./tailwind.config');

module.exports = {
   theme: { ...myDefault.theme },

   variants: {
     backgroundColor: ['dark'],
     borderColor: ['dark'],
     opacity: ['dark'],
     fontWeight: ['dark'],
     lineHeight: ['dark'],
     textColor: ['dark'],
     fontSize: ['dark'],
     fontStyle: ['dark'],
     letterSpacing: ['dark'],
   },

   plugins: [require('./src/plugins/dark-mode')()],
};
```
- As you can see, I'm adding a custom variant for generating utility classes for Dark Mode media queries.

**The problem is, the default utilities are generated too:**

Source:

```css
/* dark-mode.css */
@import 'tailwindcss/utilities';
```

Output:

```css
/* dark-mode.dist.css */

/* 👎  I don't want these: */
.bg-default {
  background-color: #f6fbfd;
}

/* ... */

/* 👍 Only these: */
@media screen and (prefers-color-scheme: dark) {
  .dark\:\.bg-default {
    background-color: #f6fbfd
  }
}
```

***

Is it possible to add an option to disable the default utilities?
